In [51]:
#Install Packages
!pip install faiss-cpu
!pip install sentence-transformers

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: faiss-cpu in /opt/anaconda3/lib/python3.12/site-packages (1.11.0.post1)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /opt/anaconda3/lib/python3.12/site-packages (from faiss-cpu) (1.26.4)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from faiss-cpu) (23.2)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: sentence-transformers in /opt/anaconda3/lib/python3.12/site-packages (5.0.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (4.53.2)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (4.66.4)
Requirement already satisfied: torch>=1.11.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (2.7.1)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (1.4.2)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (0.33.4)
Requirement already satisfied: Pillow in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (4.14.1)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.13.1)
Requirement already satisfied: numpy>=1.17 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2023.10.3)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.3.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.5)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (69.5.1)
Requirement already satisfied: sympy>=1.13.3 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.7.4)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn->sentence-transformers) (2.2.0)

In [53]:
# import necessary libraries
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [59]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [61]:
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel

In [63]:
!pip install sentence_transformers

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: sentence_transformers in /opt/anaconda3/lib/python3.12/site-packages (5.0.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence_transformers) (4.53.2)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.12/site-packages (from sentence_transformers) (4.66.4)
Requirement already satisfied: torch>=1.11.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence_transformers) (2.7.1)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.12/site-packages (from sentence_transformers) (1.4.2)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from sentence_transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence_transformers) (0.33.4)
Requirement already satisfied: Pillow in /opt/anaconda3/lib/python3.12/site-packages (from sentence_transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence_transformers) (4.14.1)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (3.13.1)
Requirement already satisfied: numpy>=1.17 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2023.10.3)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2.32.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /opt/anaconda3/lib/python3.12/site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2024.3.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (1.1.5)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence_transformers) (69.5.1)
Requirement already satisfied: sympy>=1.13.3 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence_transformers) (3.2.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence_transformers) (3.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (2024.7.4)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn->sentence_transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn->sentence_transformers) (2.2.0)

In [65]:
!pip uninstall -y keras

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Found existing installation: keras 3.10.0
Uninstalling keras-3.10.0:
  Successfully uninstalled keras-3.10.0

In [67]:
!pip install tf-keras

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: tf-keras in /opt/anaconda3/lib/python3.12/site-packages (2.19.0)
Requirement already satisfied: tensorflow<2.20,>=2.19 in /opt/anaconda3/lib/python3.12/site-packages (from tf-keras) (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (24.12.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.4.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (4.25.8)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.32.2)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (69.5.1)
Requirement already satisfied: six>=1.12.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (4.14.1)
Requirement already satisfied: wrapt>=1.11.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.63.2)
Requirement already satisfied: tensorboard~=2.19.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.19.0)
Collecting keras>=3.5.0 (from tensorflow<2.20,>=2.19->tf-keras)
  Using cached keras-3.10.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.11.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (2024.7.4)
Requirement already satisfied: markdown>=2.6.8 in /opt/anaconda3/lib/python3.12/site-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.0.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/anaconda3/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow<2.20,>=2.19->tf-keras) (0.43.0)
Requirement already satisfied: rich in /opt/anaconda3/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (14.0.0)
Requirement already satisfied: namex in /opt/anaconda3/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.0.8)
Requirement already satisfied: optree in /opt/anaconda3/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.14.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (2.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.1.0)
Using cached keras-3.10.0-py3-none-any.whl (1.4 MB)
Installing collected packages: keras
Successfully installed keras-3.10.0

In [71]:
from sentence_transformers import SentenceTransformer

In [73]:
encoder = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
vectors = encoder.encode(df.text)

In [74]:
vectors.shape

(8, 768)

In [77]:
vectors

array([[-0.00247386,  0.03626726, -0.05290461, ..., -0.0915236 ,
        -0.03970009, -0.04330486],
       [-0.03357261,  0.00980522, -0.03250133, ..., -0.05165472,
         0.02245888, -0.03156187],
       [-0.01865335, -0.04051298, -0.01235388, ...,  0.00610581,
        -0.07179651,  0.02773849],
       ...,
       [-0.00066459,  0.04252124, -0.05645506, ...,  0.01315469,
        -0.03183556, -0.04357659],
       [-0.03317151,  0.03252463, -0.02484837, ...,  0.01174422,
         0.05747118,  0.00571025],
       [-0.00166393,  0.00413834, -0.04597077, ...,  0.02008527,
         0.05656247, -0.00161594]], dtype=float32)

In [79]:
vectors[1]

array([-3.35726142e-02,  9.80522204e-03, -3.25013250e-02,  1.86820347e-02,
        1.77040845e-02, -3.62626687e-02, -3.62390615e-02,  7.10840523e-02,
        2.47629602e-02,  2.63498500e-02, -1.21423870e-03, -1.13375084e-02,
       -1.15268948e-02,  1.43791353e-02, -4.38231118e-02, -2.79518887e-02,
        1.75678506e-02, -4.70075803e-03,  8.76717195e-02,  4.92547522e-04,
       -4.46607731e-02, -3.32105793e-02, -1.42118596e-02,  2.29376610e-02,
       -8.52664094e-03, -2.48494046e-03,  8.57962761e-03,  2.66635008e-02,
        2.85465922e-02, -2.94708051e-02, -4.25881967e-02,  1.92414615e-02,
       -2.21508536e-02, -5.22683226e-02,  9.17420437e-07, -2.53167879e-02,
       -5.45516610e-02,  6.14560694e-02, -1.15586063e-02,  1.64797045e-02,
        6.11990516e-04, -6.41633943e-02, -2.64592208e-02,  2.86634751e-02,
       -7.40521681e-03, -3.89426239e-02, -8.28322081e-04,  1.00291826e-01,
       -6.97325310e-03,  2.48220470e-02,  1.85312554e-02, -5.47105912e-03,
        2.40095090e-02, -1.84511449e-02,  4.09858860e-02, -2.26923414e-02,
        2.95914784e-02,  1.59890000e-02,  2.98418608e-02,  6.38907999e-02,
        2.58491412e-02, -3.26031223e-02, -8.26758053e-03,  5.34260236e-02,
       -4.43783328e-02, -9.29070078e-03, -2.35452075e-02, -6.82238266e-02,
        1.14495475e-02,  4.07651514e-02, -4.92770225e-02,  2.56418902e-02,
        7.01447427e-02, -3.31851132e-02,  1.11843832e-02, -2.03785542e-02,
        8.65227450e-03, -1.02374898e-02, -3.91493924e-02, -4.53192741e-03,
        6.19241111e-02, -1.92383640e-02, -7.00164726e-03, -3.73338275e-02,
        2.08828021e-02, -3.45127657e-03,  1.20090935e-02,  8.63273162e-03,
        2.55907215e-02, -7.73453037e-04, -2.50837561e-02, -1.45643819e-02,
        2.38880701e-02, -1.44668436e-02,  4.12997901e-02, -1.22156888e-02,
        2.48460677e-02, -1.27597782e-03,  7.00067077e-03, -6.49261773e-02,
        2.03954000e-02,  6.89087138e-02,  1.03071555e-02, -7.91797973e-03,
       -9.52252839e-03, -2.54794974e-02, -2.35271994e-02,  4.67379801e-02,
        3.67013365e-02,  1.30289625e-02, -2.51294747e-02, -3.32402671e-03,
       -4.83352169e-02, -1.34265246e-02,  5.17111681e-02,  8.55914783e-03,
       -1.43931247e-02, -3.62585373e-02, -2.90623400e-02, -2.76030786e-02,
       -2.99808718e-02, -2.20756587e-02,  4.96576056e-02, -3.21929194e-02,
       -9.27773956e-03,  1.07672498e-01,  6.93933340e-03, -2.09447332e-02,
       -1.50242774e-02, -7.78932031e-03, -4.06213524e-03, -9.77014005e-03,
        1.80494729e-02,  3.87828760e-02,  6.88608289e-02, -1.21670337e-02,
        1.63725484e-02,  2.72275209e-02, -1.64821773e-04, -5.20296842e-02,
        5.57820825e-03,  6.28697947e-02,  4.01385576e-02,  2.15966348e-02,
        1.60552952e-02, -6.71956390e-02,  6.08031005e-02,  2.02237200e-02,
       -1.00795738e-02,  3.07943635e-02, -5.42099960e-02, -2.35007312e-02,
        6.47096038e-02,  4.73307148e-02, -1.16421226e-02,  1.20284921e-02,
       -1.03539508e-03,  8.15587060e-04,  3.34849842e-02, -3.34858801e-03,
       -1.36475293e-02,  1.85881127e-02,  6.27409026e-04,  2.10219342e-02,
        2.19755545e-02, -6.37721717e-02, -4.20541912e-02,  1.11972727e-02,
        2.76469234e-02, -2.06915792e-02,  1.17304772e-02,  1.21852001e-02,
       -2.80880718e-03,  3.82275973e-03,  4.42133881e-02,  2.25189282e-03,
        1.64212584e-02,  4.04513963e-02, -1.79602634e-02, -7.82542601e-02,
        5.79525456e-02,  1.68868005e-02, -1.76530331e-02,  4.30391431e-02,
       -1.27998544e-02,  7.48297051e-02, -8.10292661e-02, -6.17440091e-03,
       -2.06080675e-02,  1.14899976e-02, -2.12891214e-02,  1.01898657e-02,
       -4.45374899e-04, -5.92542961e-02,  1.08465366e-02,  2.14393493e-02,
       -4.67461068e-03,  5.09279035e-03,  2.59107705e-02, -1.23135804e-03,
        3.46984453e-02,  4.84393314e-02,  4.25007136e-04, -5.86432070e-02,
       -1.03664845e-02, -1.32832984e-02,  5.68065159e-02, -2.38216911e-02,
        6.42868653e-02,  1.16533553e-03, -8.26229621e-03, -2.17430722e-02,
        2.42559817e-02, -1.78288594e-02,  2.32254341e-02,  1.09582096e-02,
       -2.69017257e-02,  1.30435824e-02, -1.92239489e-02, -4.67373319e-02,
       -1.19906943e-02,  6.35164417e-03, -3.37472893e-02, -1.60461925e-02,
       -2.21641101e-02,  3.27046067e-02,  1.85040068e-02,  1.92524418e-02,
       -1.62674729e-02, -3.93539891e-02,  1.11169973e-03,  5.33456989e-02,
       -2.80959066e-02,  3.41474675e-02,  2.11112145e-02, -1.97415929e-02,
        3.02267596e-02,  2.78305691e-02, -1.52913090e-02,  1.05081666e-02,
       -2.53359228e-02, -1.49588166e-02, -1.86072886e-02, -1.70138106e-03,
       -6.39693812e-02,  1.89983007e-02,  6.96384860e-03,  2.15710215e-02,
       -8.01059455e-02,  3.16441357e-02,  6.58215396e-03,  2.29354482e-02,
       -6.36439100e-02,  4.40608710e-02, -4.14929464e-02,  2.03898139e-02,
       -4.32550348e-02, -7.20883859e-03,  5.76045848e-02,  4.60609086e-02,
        1.07085705e-02, -1.04496684e-02,  1.93596482e-02,  3.72252241e-02,
        3.87210995e-02, -1.61042288e-02, -1.93750504e-02, -1.58328041e-02,
       -2.59766914e-02, -3.51572670e-02, -1.05289035e-02,  5.26699936e-03,
        5.22579327e-02,  2.88645364e-02, -3.21052447e-02, -2.01181415e-02,
        6.11137226e-02,  2.03792918e-02,  4.92633618e-02, -2.09874921e-02,
       -1.23223504e-02,  8.61942023e-02,  7.55282864e-02,  5.98213263e-02,
        5.40041365e-02,  2.02715071e-03, -2.26158816e-02,  1.46394838e-02,
        1.10510647e-01, -4.29654755e-02,  3.88653167e-02,  1.33246277e-02,
        1.54906800e-02,  5.04894815e-02, -3.91640663e-02,  6.13814294e-02,
        5.43447137e-02, -3.36847454e-02,  1.85182858e-02, -1.10968716e-01,
       -2.50393581e-02, -3.84911918e-03,  4.61405851e-02,  1.21499849e-02,
       -1.56652667e-02,  3.85172367e-02,  1.91747602e-02,  3.39069143e-02,
       -2.96352264e-02,  4.14793566e-02,  2.15318557e-02,  2.93096751e-02,
        1.71868578e-02, -3.59830447e-02,  2.18271241e-02,  4.28997837e-02,
       -5.75206131e-02, -1.92242619e-02,  2.12443601e-02,  2.04696949e-03,
       -5.68150217e-03,  2.48145480e-02, -3.16320434e-02, -4.43522856e-02,
        2.27882862e-02, -3.34307842e-04,  8.58257711e-03, -4.02720906e-02,
       -3.79484631e-02, -4.34352830e-02,  1.28198974e-03,  2.07371619e-02,
        7.17612728e-02,  1.84787449e-03,  3.51873599e-02,  8.62419885e-03,
        1.60184857e-02,  5.75456843e-02, -1.25773642e-02,  1.02894660e-02,
       -1.69317741e-02, -9.37231109e-02, -3.49836797e-02, -2.44941730e-02,
        1.23326713e-02,  1.46685885e-02,  4.08049226e-02,  2.50652595e-03,
        5.45818582e-02,  2.91737206e-02, -5.39811375e-03, -2.85476558e-02,
       -2.34896019e-02, -1.07574870e-03,  4.24961065e-04, -6.98285922e-02,
        1.25891669e-02, -3.92431160e-03, -4.81126159e-02,  1.90331079e-02,
        6.65107183e-03, -3.88475158e-03, -1.05894674e-02, -5.17404303e-02,
        5.32847829e-02, -8.30340106e-03, -8.85912857e-04, -9.18868743e-03,
       -7.28048338e-03,  5.55177126e-03, -1.56909656e-02,  3.09270788e-02,
       -4.40982394e-02,  1.02480361e-02,  1.52976615e-02, -1.30980751e-02,
        2.13123616e-02, -6.71373978e-02, -1.81569159e-02,  3.22471261e-02,
        2.95263994e-02,  5.68892108e-03,  2.05119364e-02,  6.43818220e-03,
       -2.22543459e-02,  2.13126577e-02,  3.21273394e-02, -6.24837354e-02,
        1.68938786e-02, -6.13404959e-02,  1.47031322e-02, -1.53157450e-02,
       -1.03139249e-03, -2.83481665e-02, -2.39032358e-02, -1.70185491e-02,
        1.88786518e-02, -7.34043494e-02, -5.25554605e-02,  1.53817898e-02,
        1.30274314e-02, -3.96441109e-02,  5.24452142e-02, -2.49939971e-02,
        2.74955947e-02,  3.60509753e-02,  5.73946238e-02,  2.25475300e-02,
        3.25942859e-02,  8.90985690e-03,  5.43262437e-02,  2.10294351e-02,
        2.16910802e-02, -3.01539320e-02,  2.19052541e-03,  3.80706862e-02,
        4.07610945e-02,  7.83905387e-02,  5.29225506e-02, -4.02739607e-02,
       -7.14954063e-02,  5.61715513e-02, -5.62878475e-02,  4.30115238e-02,
       -1.81321055e-02, -7.10935565e-03,  5.61597720e-02, -1.29609471e-02,
       -6.05658777e-02,  1.40673239e-02,  4.54457924e-02,  3.30817215e-02,
       -4.44654003e-03, -1.04194552e-01,  6.20512627e-02, -8.04488920e-03,
        2.53955405e-02, -5.35988398e-02, -2.87731178e-03,  5.55383414e-02,
       -4.69393376e-03,  3.03412024e-02,  3.86410169e-02, -3.07783615e-02,
        3.70677784e-02,  7.07896948e-02,  1.62174292e-02,  1.07857995e-01,
       -4.73799631e-02, -1.05365831e-02, -9.48570203e-03,  5.85111007e-02,
        2.26293281e-02, -5.49605116e-04, -3.41104828e-02, -8.44275486e-03,
        2.09487416e-02, -2.25966945e-02,  7.02017024e-02, -1.75867081e-02,
        4.84230928e-02,  3.07194865e-03,  4.45459895e-02,  2.11489331e-02,
        5.86253777e-03, -2.15045325e-02, -1.92374606e-02,  2.49662548e-02,
        7.70032965e-03, -5.85462786e-02, -4.48391587e-03,  2.40318943e-02,
       -2.65536271e-03, -1.13359578e-02,  5.13387024e-02, -6.58841291e-03,
       -4.52473760e-02,  2.38739122e-02, -6.40834793e-02,  4.75434447e-03,
       -3.28243226e-02,  1.94960982e-02, -5.79635799e-03, -6.90020621e-02,
       -1.13662984e-02,  3.52125131e-02, -6.56303689e-02, -1.65679995e-02,
        1.50974561e-02,  7.77235553e-02, -4.23436873e-02,  7.64394319e-03,
        1.68971792e-02, -6.57750145e-02, -1.03674512e-02, -1.54936779e-02,
       -6.73222467e-02, -1.95327718e-02, -2.35322956e-02,  2.75447443e-02,
       -5.01309782e-02, -2.43230797e-02,  4.12268974e-02,  5.34089506e-02,
        1.23127392e-02,  1.25194062e-02, -1.95430145e-02,  4.38058563e-02,
        2.56417487e-02, -1.93017665e-02, -5.73117286e-02, -2.95281298e-02,
       -1.08611874e-01,  1.43510941e-02,  3.20817567e-02,  9.96927023e-02,
        6.22826852e-02,  1.15520721e-02, -1.72614623e-02, -2.42948998e-02,
       -7.28665199e-03, -2.44392641e-02,  1.16017330e-02,  4.81274910e-02,
        4.65680001e-04,  4.60677296e-02, -2.64352337e-02,  2.17289943e-03,
       -3.03759798e-02,  3.96300629e-02, -1.91512965e-02, -2.66074594e-02,
        5.60491495e-02, -5.37889674e-02, -8.28454830e-03,  2.28182282e-02,
       -1.35340067e-02,  5.61504960e-02, -5.94904041e-03,  1.97246037e-02,
        2.47832737e-03, -2.38718241e-02,  4.05481011e-02,  4.94958200e-02,
        3.03312670e-02, -4.49723341e-02, -8.13962966e-02, -7.77650112e-03,
       -4.09913138e-02, -9.98651329e-03,  2.02550981e-02,  9.42017511e-03,
       -1.03325441e-01,  1.56904683e-02, -7.34916516e-03, -4.28104206e-33,
        1.84916938e-03,  2.49899961e-02,  4.30825278e-02, -1.80863426e-03,
        1.06527187e-01,  5.75299226e-02,  2.23685754e-03, -8.82520247e-03,
       -2.76356563e-02,  4.49949987e-02, -7.76133239e-02, -4.94545586e-02,
        4.29597823e-03, -6.67969957e-02, -1.07111037e-02, -3.80072445e-02,
        2.97382358e-03,  1.90955948e-03, -2.09461506e-02, -3.26110497e-02,
       -6.88911676e-02,  3.32696326e-02, -4.44098003e-02,  7.68893436e-02,
        1.98380966e-02,  4.43438217e-02,  1.16210002e-02, -3.89219611e-03,
       -8.83540325e-03,  3.02967392e-02,  2.04690304e-02, -2.44675484e-03,
        7.54141808e-03, -1.81705989e-02, -1.13567915e-02,  2.20167562e-02,
       -3.76540013e-02,  7.88017269e-03, -2.76778243e-03, -4.65984009e-02,
       -2.39178967e-02,  4.27089594e-02,  1.27477506e-02, -3.49133206e-03,
       -1.73228793e-03,  5.32612728e-04,  1.37985507e-02, -5.88246584e-02,
       -2.32382473e-02, -8.74427240e-03, -1.77632067e-02, -1.31566469e-02,
        3.03805731e-02,  4.22015078e-02, -6.73772488e-03,  1.11841327e-02,
       -8.27119127e-03, -3.78280729e-02, -1.24693746e-02, -4.14636694e-02,
       -1.26111915e-03,  4.64669280e-02, -7.82364607e-02,  2.05411091e-02,
       -7.02480320e-03, -1.06605804e-02, -4.50240821e-02, -4.22418900e-02,
       -2.15095188e-03, -2.40540821e-02, -4.69919555e-02, -6.05253242e-02,
        5.82413897e-02,  2.95025092e-02, -7.44162733e-03, -1.00766324e-01,
       -3.92184295e-02,  3.07860021e-02,  4.28364333e-03, -7.42603615e-02,
       -5.22072017e-02, -3.43477516e-03,  3.15366611e-02,  3.49473283e-02,
       -6.93784468e-03,  7.32728699e-03, -3.23810354e-02, -1.72191709e-02,
       -3.54516096e-02, -1.90520342e-02,  2.62780115e-02,  1.63122844e-02,
        4.35292013e-02,  1.06643774e-02, -2.23603081e-02,  3.37389968e-02,
       -6.16681855e-03, -8.26238394e-02,  2.66042687e-02, -8.35096557e-03,
       -1.83438864e-02,  2.00079894e-03,  5.02547063e-02,  3.45277712e-02,
       -3.72373536e-02,  2.92173531e-02,  1.72079017e-03, -1.58035289e-02,
        1.14710517e-02, -1.25145540e-02, -4.20715772e-02,  4.86484133e-02,
        2.28662416e-02, -4.68053855e-03, -4.26828600e-02, -1.28418207e-02,
        7.45493397e-02,  3.06699574e-02,  1.45301819e-02, -6.23452663e-02,
       -1.26675395e-02,  3.36178727e-02,  6.05070107e-02, -3.02765816e-02,
       -3.71763259e-02, -4.64073233e-02,  8.39665085e-02,  9.42517631e-03,
       -3.21013741e-02,  8.08133278e-03,  5.02915010e-02,  1.75022688e-02,
        1.57571719e-07, -1.98554862e-02, -2.83059664e-02,  2.90523432e-02,
       -3.78218852e-02, -5.00640944e-02,  4.02771588e-03, -1.18794898e-02,
       -1.46822901e-02,  1.81088895e-02,  2.68273428e-02,  9.23964381e-03,
       -2.70948838e-02,  2.32513621e-03, -1.62717011e-02,  3.18160243e-02,
       -3.51314507e-02, -2.04745214e-02, -4.17290926e-02,  1.66735314e-02,
       -3.71345840e-02,  4.71012630e-02,  1.73169840e-02, -5.56524098e-02,
       -4.02241684e-02, -5.00142314e-02,  4.97486740e-02, -1.61511507e-02,
       -6.62214495e-03, -4.74094823e-02, -3.85605656e-02,  1.55845573e-02,
        4.09969408e-03,  1.63189042e-02, -3.17491889e-02, -6.53794259e-02,
       -2.32730322e-02, -2.41440218e-02, -2.17096601e-02, -4.34638299e-02,
        5.88003658e-02,  8.67548957e-03,  5.04563525e-02, -1.48966564e-02,
       -3.00932527e-02, -4.45601251e-03, -4.09636199e-02, -4.19238806e-02,
       -4.22753841e-02,  1.00178488e-01, -2.62382068e-02, -3.23651731e-03,
        3.29558067e-02, -3.81884840e-03, -1.64519660e-02, -3.44150364e-02,
        2.69218832e-02, -3.18483487e-02,  5.79118589e-03,  5.21225668e-02,
       -5.56408912e-02,  2.18991488e-02,  1.57098956e-02,  7.62978429e-03,
       -1.67025570e-02, -6.40249671e-03,  4.05184589e-02, -4.84588146e-02,
        1.24100474e-34, -3.20822671e-02, -5.96444644e-02, -1.55761242e-02,
       -5.08974530e-02,  1.69498101e-02,  6.91906130e-03,  8.61440226e-03,
        6.02010079e-02, -5.16547188e-02,  2.24588849e-02, -3.15618701e-02],
      dtype=float32)

In [81]:
vectors.shape[1]

768

In [83]:
dim = vectors.shape[1]
dim

768

In [89]:
import faiss

index = faiss.IndexFlatL2(dim)
index

In [91]:
index.add(vectors)

In [93]:
search_query = "I want to buy a polo t-shirt"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [95]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [99]:
distances, I = index.search(svec, k=2)

In [101]:
I

array([[3, 2]])

In [103]:
df.loc[I[0]]

                                                text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [105]:
search_query

'I want to buy a polo t-shirt'

In [107]:
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel

In [97]:
index.search(svec,k=2)

(array([[1.3844836, 1.4039094]], dtype=float32), array([[3, 2]]))

In [35]:
faiss.normalize_L2(svec)

In [39]:
distances, I = index.search(svec, k=2)
distances

array([[1.3844839, 1.4039096]], dtype=float32)

In [41]:
I

array([[3, 2]])

In [43]:
I.tolist()

[[3, 2]]

In [45]:
row_indices = I.tolist()[0]
row_indices

[3, 2]

In [47]:
df.loc[row_indices]

                                                text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [49]:
search_query

'I want to buy a polo t-shirt'